# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  push:
    paths-ignore:
      - "notes.md"
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/workflow/install_venv.yml
      env:
        VAULT_PASS: ${{ secrets.ola_default }} 
