name: Deploy

on:
  push:
    paths-ignore:
      - "notes.md"
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Cache
        uses: actions/cache@v1
        id: cache
        with:
          path: ./env
          key: ${{ runner.os }}-env-v2-${{ hashFiles('**/requirements.txt') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Run Tests
        run: |
          source env/bin/activate
          pytest -sx -n 2
      - name: Output SSH key to file
        run: |
          mkdir ~/.ssh
          echo "${{secrets.ola_default}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy via ansible
        working-directory: ./ansible
        run: ansible-playbook install_venv.yml -i hosts_github
